/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package converter;

import java.io.FileNotFoundException;
import java.util.Currency;
import java.util.HashMap;
import java.util.List;

public class Exchange {
    
    private List<User> users;
    private List<Currency> currencies;
    private HashMap<Currency, HashMap<Currency, Double>> rates;
    private Currency[] popularCurrencies;

    public User getUser(String username) throws FileNotFoundException {

        for (int i = 0; i < users.size(); i++) {

            if (users.get(i).getUsername().equals(username)) {
                return users.get(i);
            }
        }

        throw new FileNotFoundException("There is no such user in the system");
    }
}
